### ISSUE TITLE
RELEASES.json does not exist

### ISSUE THREAD

**Issue by Stoyvo** [atlassian/nucleus#26]
Within the channel, the `Updater Usage` section has reference to a RELEASES.json file. This does not exist in the purposed location.

**Comment by Stoyvo** [comment]
While reading the code here: https://github.com/atlassian/nucleus/blob/master/uploader/src/index.js#L37

I realize that maybe Nucleus is supposed to generate the RELEASES.json file, however this is not the case.

How do I find more information about when this file is generated?

**Comment by MarshallOfSound** [comment]
@Stoyvo Have you uploaded / released a version of your app with a Mac artifact.  In order to generate the releases file you need to release at least one thing

**Comment by Stoyvo** [comment]
@MarshallOfSound Yes, there are two .dmg uploads (different versions, 0.0.1-alpha.1, 0.0.1-alpha.2)

I thing I noticed is that .zip files are also classified as .dmg files within the UI, haven't checked the temp files.

**Comment by MarshallOfSound** [comment]
@stoyvo Are they actually released or just in the "draft" section?

**Comment by Stoyvo** [comment]
@MarshallOfSound actually in the release section. Currently 2 are marked as dead, 1 is 100 rollout.

I have 3 release channels: alpha, beta, latest. I have only released to alpha.

Can you point me to where the RELEASES.json file is generated? I might be able to assist the debug

**Comment by MarshallOfSound** [comment]
@Stoyvo Only `zip` files will cause the `RELEASES.json` file to be generated (those are the files that go into that file)

https://github.com/atlassian/nucleus/blob/master/src/files/Positioner.ts#L112

**Comment by MarshallOfSound** [comment]
@Stoyvo You can also run nucleus with `DEBUG=nucleus*` to get a whole bunch of handy logs 😄

**Comment by Stoyvo** [comment]
@MarshallOfSound ah, yes, thank you. I was pushing up the dmg, not the zip. Much appreciated.

Closing out ticket.

**Comment by teaxio** [comment]
[I can open a new issue if you like, I just thought for continuity, this is best place]
@MarshallOfSound @Stoyvo I am using electron-forge `6.0.0-beta.54`, how are you generating a zip? I am `using maker-dmg` with this config:
```
{
          "name": "@electron-forge/maker-dmg",
          "config": {
            "category": "public.app-category.utilities",
            "icon": "build/icons/icon.icns",
            "title": "My App",
            "overwrite": true
          }
        }
```
How do you tell it to generate a zip rather than dmg? Or are you using `maker-zip`? If you are, I thought that `maker-zip` does not include the actual dmg in it, but it is just the content of the dmg. This defeats the purpose of how the user will easily install this, no? Or do I need a `postMake` hook?
I think there is something I am missing in this picture. If you could please guide me.
